import '@ionic/core';
import 'aframe';
import 'simple-buttons/dist/simple-button';
import(/* webpackPreload: true */ '@polymer/paper-styles/paper-styles');
import(/* webpackPreload: true */ '@polymer/paper-progress/paper-progress');
import(/* webpackPreload: true */ '@polymer/paper-button/paper-button.js');
import(/* webpackPreload: true */ '@polymer/paper-icon-button/paper-icon-button.js');
import(/* webpackPreload: true */ '@polymer/iron-icons/iron-icons.js');
import(/* webpackPreload: true */ '@polymer/iron-icons/social-icons.js');
import(/* webpackPreload: true */ '@polymer/paper-card');
import('aframe-environment-component');
