apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: registry.gitlab.com/mhdev/k8s-playground/leeroy-web
    context: ./leeroy-web/
  - image: registry.gitlab.com/mhdev/k8s-playground/leeroy-app
    context: ./leeroy-app/
deploy:
  kubectl:
    manifests:
    - ./leeroy-web/kubernetes/*-dist.yaml
    - ./leeroy-app/kubernetes/*-dist.yaml
