{
  "name": "wc-bundler-bundle",
  "version": "1.0.0",
  "description": "Autogenerated Web Components Bundle",
  "scripts": {
    "build": "rm -rf ./dist/ && webpack --mode production --config webpack.config.js",
    "dev": "webpack-dev-server --mode development --config webpack.config.js"
  },
  "devDependencies": {
    "@stencil/webpack": "0.0.6",
    "html-webpack-plugin": "^3.2.0",
    "webpack": "^4.27.0",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.10"
  },
  "dependencies": {
    "@ionic/core": "^4.0.0-beta.17"
  }
}
