FROM phpdockerio/php7-fpm:latest

# POST and max upload sizes on php.ini
RUN sed -i "/upload_max_filesize = .*/c\upload_max_filesize = 100M" /etc/php/7.0/fpm/php.ini \
    && sed -i "/post_max_size = .*/c\post_max_size = 108M" /etc/php/7.0/fpm/php.ini

# Install selected extensions and other stuff
RUN apt-get update \
    && apt-get -y --no-install-recommends install  php7.0-mysql php7.0-redis php7.0-imagick \
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*


WORKDIR "/var/www"
